### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by SteveScott** [ntegral/strapi-provider-upload-azure-storage-blob#2]
I was able to make the content block error go away by adding Azure to the middleware. However, I am getting this other error which is preventing the Media Library page from loading. Would you be able to make sense of this minified JS script exception?
```
main.940c6c72.js:2 
        
       TypeError: Cannot read properties of null (reading 'split')
    at p (main.940c6c72.js:2:1225604)
    at li (main.940c6c72.js:2:2202187)
    at $u (main.940c6c72.js:2:2254484)
    at kl (main.940c6c72.js:2:2241725)
    at Pl (main.940c6c72.js:2:2241653)
    at Sl (main.940c6c72.js:2:2241516)
    at Ol (main.940c6c72.js:2:2238482)
    at main.940c6c72.js:2:2187979
    at t.unstable_runWithPriority (main.940c6c72.js:2:2388775)
    at Vo (main.940c6c72.js:2:2187756)
fu @ main.940c6c72.js:2
```

**Comment by SteveScott** [comment]
Please see issue #12761 in the strapi issues page. Re-install did not work. Do I need to reinstall strapi-provider-upload-azure-storage-blob?
